// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  group("Rate limiter", function() {
    postman[Request]({
      name: "0.1 rps",
      id: "a5a64c23-a6c9-4167-9b90-e06882068428",
      method: "GET",
      address: "http://localhost:8080/quota/test-low"
    });

    postman[Request]({
      name: "1 rps",
      id: "c31c0cae-f460-44ba-ac0c-e5061ea0dba4",
      method: "GET",
      address: "http://localhost:8080/quota/test-1"
    });

    postman[Request]({
      name: "30 rps",
      id: "0089ff2f-4218-4247-bae1-5855aa3de888",
      method: "GET",
      address: "http://localhost:8080/quota/test-30"
    });
  });
}
